/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PriceChange = IDL.Record({
  'currentPrice' : IDL.Float64,
  'difference' : IDL.Float64,
  'previousPrice' : IDL.Float64,
});
export const CityPrice = IDL.Record({
  'city' : IDL.Text,
  'lastUpdated' : IDL.Text,
  'priceINR' : IDL.Float64,
  'priceChange' : PriceChange,
});
export const Time = IDL.Int;
export const NewsCategory = IDL.Variant({
  'safety' : IDL.Null,
  'scheme' : IDL.Null,
  'price' : IDL.Null,
  'policy' : IDL.Null,
});
export const NewsItem = IDL.Record({
  'title' : IDL.Text,
  'date' : Time,
  'summary' : IDL.Text,
  'category' : NewsCategory,
});
export const SafetyTip = IDL.Record({
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const Scheme = IDL.Record({
  'link' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'eligibility' : IDL.Text,
  'benefits' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllCityPrices' : IDL.Func([], [IDL.Vec(CityPrice)], ['query']),
  'getAllNewsItems' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
  'getAllSafetyTips' : IDL.Func([], [IDL.Vec(SafetyTip)], ['query']),
  'getAllSchemes' : IDL.Func([], [IDL.Vec(Scheme)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PriceChange = IDL.Record({
    'currentPrice' : IDL.Float64,
    'difference' : IDL.Float64,
    'previousPrice' : IDL.Float64,
  });
  const CityPrice = IDL.Record({
    'city' : IDL.Text,
    'lastUpdated' : IDL.Text,
    'priceINR' : IDL.Float64,
    'priceChange' : PriceChange,
  });
  const Time = IDL.Int;
  const NewsCategory = IDL.Variant({
    'safety' : IDL.Null,
    'scheme' : IDL.Null,
    'price' : IDL.Null,
    'policy' : IDL.Null,
  });
  const NewsItem = IDL.Record({
    'title' : IDL.Text,
    'date' : Time,
    'summary' : IDL.Text,
    'category' : NewsCategory,
  });
  const SafetyTip = IDL.Record({
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const Scheme = IDL.Record({
    'link' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'eligibility' : IDL.Text,
    'benefits' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllCityPrices' : IDL.Func([], [IDL.Vec(CityPrice)], ['query']),
    'getAllNewsItems' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
    'getAllSafetyTips' : IDL.Func([], [IDL.Vec(SafetyTip)], ['query']),
    'getAllSchemes' : IDL.Func([], [IDL.Vec(Scheme)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };