/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CityPrice {
  'city' : string,
  'lastUpdated' : string,
  'priceINR' : number,
  'priceChange' : PriceChange,
}
export type NewsCategory = { 'safety' : null } |
  { 'scheme' : null } |
  { 'price' : null } |
  { 'policy' : null };
export interface NewsItem {
  'title' : string,
  'date' : Time,
  'summary' : string,
  'category' : NewsCategory,
}
export interface PriceChange {
  'currentPrice' : number,
  'difference' : number,
  'previousPrice' : number,
}
export interface SafetyTip {
  'title' : string,
  'icon' : string,
  'description' : string,
}
export interface Scheme {
  'link' : string,
  'name' : string,
  'description' : string,
  'eligibility' : string,
  'benefits' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllCityPrices' : ActorMethod<[], Array<CityPrice>>,
  'getAllNewsItems' : ActorMethod<[], Array<NewsItem>>,
  'getAllSafetyTips' : ActorMethod<[], Array<SafetyTip>>,
  'getAllSchemes' : ActorMethod<[], Array<Scheme>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];